### ISSUE TITLE
Add 'official' [improvement]

### ISSUE THREAD

**Issue by digaogt** [Collabsvito/Repo#3]
Hi, Vito.
Thank you so much for your amazing addon.
I just would like to suggest you to add 'official' before the title in the playYTByTitle:

def playYTByTitle(title):
	try:
		youtubeID = getYoutubeId('official '+title)

It makes lots of differences when searching for the right music video on Youtube, avoiding live concerts.

**Comment by Collabsvito** [comment]
@digaogt 

Sorry, for the late reaction.

I will test it and if it is good, I will integrate it into the next release.

Thanks

**Comment by Collabsvito** [comment]
Accepted in v.2.1.3 of Youtube Music.
