### ISSUE TITLE
ATV Mediathek Video ladet nicht

### ISSUE THREAD

**Issue by wappla1911** [Collabsvito/Repo#4]
Hi,
Einsatz live Folge 8 oder 9 z.B. laden nicht... Auf ATV direkt funktioniert der Stream

**Comment by Collabsvito** [comment]
@wappla1911 
Bei mir in Deutschland funktionieren die genannten Folgen einwandfrei.
Bitte evtl. die Abspielmethode in den Einstellungen des Addons verändern, da es ab Kodi-18 bei der Standard-1-Methode Probleme gibt.
Gruß
